// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: starwars/starwars.proto

package starwars

import (
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_HUMAN Type = 0
	Type_DROID Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "HUMAN",
		1: "DROID",
	}
	Type_value = map[string]int32{
		"HUMAN": 0,
		"DROID": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_starwars_starwars_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_starwars_starwars_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{0}
}

type Episode int32

const (
	Episode__       Episode = 0
	Episode_NEWHOPE Episode = 1
	Episode_EMPIRE  Episode = 2
	Episode_JEDI    Episode = 3
)

// Enum value maps for Episode.
var (
	Episode_name = map[int32]string{
		0: "_",
		1: "NEWHOPE",
		2: "EMPIRE",
		3: "JEDI",
	}
	Episode_value = map[string]int32{
		"_":       0,
		"NEWHOPE": 1,
		"EMPIRE":  2,
		"JEDI":    3,
	}
)

func (x Episode) Enum() *Episode {
	p := new(Episode)
	*p = x
	return p
}

func (x Episode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Episode) Descriptor() protoreflect.EnumDescriptor {
	return file_starwars_starwars_proto_enumTypes[1].Descriptor()
}

func (Episode) Type() protoreflect.EnumType {
	return &file_starwars_starwars_proto_enumTypes[1]
}

func (x Episode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Episode.Descriptor instead.
func (Episode) EnumDescriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{1}
}

type Character struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Friends         []*Character           `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	AppearsIn       []Episode              `protobuf:"varint,4,rep,packed,name=appears_in,json=appearsIn,proto3,enum=startwars.Episode" json:"appears_in,omitempty"`
	HomePlanet      string                 `protobuf:"bytes,5,opt,name=home_planet,json=homePlanet,proto3" json:"home_planet,omitempty"`
	PrimaryFunction string                 `protobuf:"bytes,6,opt,name=primary_function,json=primaryFunction,proto3" json:"primary_function,omitempty"`
	Type            Type                   `protobuf:"varint,7,opt,name=type,proto3,enum=startwars.Type" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_starwars_starwars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetFriends() []*Character {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *Character) GetAppearsIn() []Episode {
	if x != nil {
		return x.AppearsIn
	}
	return nil
}

func (x *Character) GetHomePlanet() string {
	if x != nil {
		return x.HomePlanet
	}
	return ""
}

func (x *Character) GetPrimaryFunction() string {
	if x != nil {
		return x.PrimaryFunction
	}
	return ""
}

func (x *Character) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_HUMAN
}

type GetHeroRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If omitted, returns the hero of the whope saga. If provided, returns the hero of that particular episode.
	Episode       Episode `protobuf:"varint,1,opt,name=episode,proto3,enum=startwars.Episode" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeroRequest) Reset() {
	*x = GetHeroRequest{}
	mi := &file_starwars_starwars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeroRequest) ProtoMessage() {}

func (x *GetHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeroRequest.ProtoReflect.Descriptor instead.
func (*GetHeroRequest) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{1}
}

func (x *GetHeroRequest) GetEpisode() Episode {
	if x != nil {
		return x.Episode
	}
	return Episode__
}

type GetHumanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the human
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanRequest) Reset() {
	*x = GetHumanRequest{}
	mi := &file_starwars_starwars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanRequest) ProtoMessage() {}

func (x *GetHumanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanRequest.ProtoReflect.Descriptor instead.
func (*GetHumanRequest) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{2}
}

func (x *GetHumanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDroidRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the droid
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDroidRequest) Reset() {
	*x = GetDroidRequest{}
	mi := &file_starwars_starwars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDroidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroidRequest) ProtoMessage() {}

func (x *GetDroidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroidRequest.ProtoReflect.Descriptor instead.
func (*GetDroidRequest) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{3}
}

func (x *GetDroidRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmptyRequest) Reset() {
	*x = ListEmptyRequest{}
	mi := &file_starwars_starwars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmptyRequest) ProtoMessage() {}

func (x *ListEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmptyRequest.ProtoReflect.Descriptor instead.
func (*ListEmptyRequest) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{4}
}

type ListHumansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Humans        []*Character           `protobuf:"bytes,1,rep,name=humans,proto3" json:"humans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHumansResponse) Reset() {
	*x = ListHumansResponse{}
	mi := &file_starwars_starwars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHumansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHumansResponse) ProtoMessage() {}

func (x *ListHumansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHumansResponse.ProtoReflect.Descriptor instead.
func (*ListHumansResponse) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{5}
}

func (x *ListHumansResponse) GetHumans() []*Character {
	if x != nil {
		return x.Humans
	}
	return nil
}

type ListDroidsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Droids        []*Character           `protobuf:"bytes,1,rep,name=droids,proto3" json:"droids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDroidsResponse) Reset() {
	*x = ListDroidsResponse{}
	mi := &file_starwars_starwars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDroidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDroidsResponse) ProtoMessage() {}

func (x *ListDroidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_starwars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDroidsResponse.ProtoReflect.Descriptor instead.
func (*ListDroidsResponse) Descriptor() ([]byte, []int) {
	return file_starwars_starwars_proto_rawDescGZIP(), []int{6}
}

func (x *ListDroidsResponse) GetDroids() []*Character {
	if x != nil {
		return x.Droids
	}
	return nil
}

var File_starwars_starwars_proto protoreflect.FileDescriptor

const file_starwars_starwars_proto_rawDesc = "" +
	"\n" +
	"\x17starwars/starwars.proto\x12\tstartwars\x1a\x15graphql/graphql.proto\"\x83\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\afriends\x18\x03 \x03(\v2\x14.startwars.CharacterR\afriends\x121\n" +
	"\n" +
	"appears_in\x18\x04 \x03(\x0e2\x12.startwars.EpisodeR\tappearsIn\x12\x1f\n" +
	"\vhome_planet\x18\x05 \x01(\tR\n" +
	"homePlanet\x12)\n" +
	"\x10primary_function\x18\x06 \x01(\tR\x0fprimaryFunction\x12#\n" +
	"\x04type\x18\a \x01(\x0e2\x0f.startwars.TypeR\x04type\">\n" +
	"\x0eGetHeroRequest\x12,\n" +
	"\aepisode\x18\x01 \x01(\x0e2\x12.startwars.EpisodeR\aepisode\"(\n" +
	"\x0fGetHumanRequest\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xbaC\x02\b\x01R\x02id\"(\n" +
	"\x0fGetDroidRequest\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xbaC\x02\b\x01R\x02id\"\x12\n" +
	"\x10ListEmptyRequest\"B\n" +
	"\x12ListHumansResponse\x12,\n" +
	"\x06humans\x18\x01 \x03(\v2\x14.startwars.CharacterR\x06humans\"B\n" +
	"\x12ListDroidsResponse\x12,\n" +
	"\x06droids\x18\x01 \x03(\v2\x14.startwars.CharacterR\x06droids*\x1c\n" +
	"\x04Type\x12\t\n" +
	"\x05HUMAN\x10\x00\x12\t\n" +
	"\x05DROID\x10\x01*3\n" +
	"\aEpisode\x12\x05\n" +
	"\x01_\x10\x00\x12\v\n" +
	"\aNEWHOPE\x10\x01\x12\n" +
	"\n" +
	"\x06EMPIRE\x10\x02\x12\b\n" +
	"\x04JEDI\x10\x032\xc2\x03\n" +
	"\x10StartwarsService\x12E\n" +
	"\aGetHero\x12\x19.startwars.GetHeroRequest\x1a\x14.startwars.Character\"\t\xbaC\x06\x12\x04hero\x12H\n" +
	"\bGetHuman\x12\x1a.startwars.GetHumanRequest\x1a\x14.startwars.Character\"\n" +
	"\xbaC\a\x12\x05human\x12H\n" +
	"\bGetDroid\x12\x1a.startwars.GetDroidRequest\x1a\x14.startwars.Character\"\n" +
	"\xbaC\a\x12\x05droid\x12_\n" +
	"\n" +
	"ListHumans\x12\x1b.startwars.ListEmptyRequest\x1a\x1d.startwars.ListHumansResponse\"\x15\xbaC\x12\x12\x06humans\"\b\x12\x06humans\x12_\n" +
	"\n" +
	"ListDroids\x12\x1b.startwars.ListEmptyRequest\x1a\x1d.startwars.ListDroidsResponse\"\x15\xbaC\x12\x12\x06droids\"\b\x12\x06droids\x1a\x11\xbaC\x0e\n" +
	"\n" +
	"grpc:50051\x10\x01BJZHgithub.com/ysugimoto/grpc-graphql-gateway/example/starwars/spec/starwarsb\x06proto3"

var (
	file_starwars_starwars_proto_rawDescOnce sync.Once
	file_starwars_starwars_proto_rawDescData []byte
)

func file_starwars_starwars_proto_rawDescGZIP() []byte {
	file_starwars_starwars_proto_rawDescOnce.Do(func() {
		file_starwars_starwars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starwars_starwars_proto_rawDesc), len(file_starwars_starwars_proto_rawDesc)))
	})
	return file_starwars_starwars_proto_rawDescData
}

var file_starwars_starwars_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_starwars_starwars_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_starwars_starwars_proto_goTypes = []any{
	(Type)(0),                  // 0: startwars.Type
	(Episode)(0),               // 1: startwars.Episode
	(*Character)(nil),          // 2: startwars.Character
	(*GetHeroRequest)(nil),     // 3: startwars.GetHeroRequest
	(*GetHumanRequest)(nil),    // 4: startwars.GetHumanRequest
	(*GetDroidRequest)(nil),    // 5: startwars.GetDroidRequest
	(*ListEmptyRequest)(nil),   // 6: startwars.ListEmptyRequest
	(*ListHumansResponse)(nil), // 7: startwars.ListHumansResponse
	(*ListDroidsResponse)(nil), // 8: startwars.ListDroidsResponse
}
var file_starwars_starwars_proto_depIdxs = []int32{
	2,  // 0: startwars.Character.friends:type_name -> startwars.Character
	1,  // 1: startwars.Character.appears_in:type_name -> startwars.Episode
	0,  // 2: startwars.Character.type:type_name -> startwars.Type
	1,  // 3: startwars.GetHeroRequest.episode:type_name -> startwars.Episode
	2,  // 4: startwars.ListHumansResponse.humans:type_name -> startwars.Character
	2,  // 5: startwars.ListDroidsResponse.droids:type_name -> startwars.Character
	3,  // 6: startwars.StartwarsService.GetHero:input_type -> startwars.GetHeroRequest
	4,  // 7: startwars.StartwarsService.GetHuman:input_type -> startwars.GetHumanRequest
	5,  // 8: startwars.StartwarsService.GetDroid:input_type -> startwars.GetDroidRequest
	6,  // 9: startwars.StartwarsService.ListHumans:input_type -> startwars.ListEmptyRequest
	6,  // 10: startwars.StartwarsService.ListDroids:input_type -> startwars.ListEmptyRequest
	2,  // 11: startwars.StartwarsService.GetHero:output_type -> startwars.Character
	2,  // 12: startwars.StartwarsService.GetHuman:output_type -> startwars.Character
	2,  // 13: startwars.StartwarsService.GetDroid:output_type -> startwars.Character
	7,  // 14: startwars.StartwarsService.ListHumans:output_type -> startwars.ListHumansResponse
	8,  // 15: startwars.StartwarsService.ListDroids:output_type -> startwars.ListDroidsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_starwars_starwars_proto_init() }
func file_starwars_starwars_proto_init() {
	if File_starwars_starwars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starwars_starwars_proto_rawDesc), len(file_starwars_starwars_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starwars_starwars_proto_goTypes,
		DependencyIndexes: file_starwars_starwars_proto_depIdxs,
		EnumInfos:         file_starwars_starwars_proto_enumTypes,
		MessageInfos:      file_starwars_starwars_proto_msgTypes,
	}.Build()
	File_starwars_starwars_proto = out.File
	file_starwars_starwars_proto_goTypes = nil
	file_starwars_starwars_proto_depIdxs = nil
}
